import type { Metadata } from 'next';
import { Rubik, Geist_Mono } from 'next/font/google';
import './globals.css';

import { SessionProvider } from '@/app/lib/context/session';

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

const spaceMono = Geist_Mono({
  variable: '--font-space-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${rubik.variable} ${spaceMono.variable} antialiased`}>
     
     
          <SessionProvider>{children}</SessionProvider>
     
      </body>
    </html>
  );
}
